api/urls.py
from django.conf.urls import url
import api.views

urlpatterns = [
    url(r'^(?P<kind>manifests$)', api.views.plist_api),
    url(r'^(?P<kind>manifests)/(?P<filepath>.*$)', api.views.plist_api),
    url(r'^(?P<kind>pkgsinfo$)', api.views.plist_api),
    url(r'^(?P<kind>pkgsinfo)/(?P<filepath>.*$)', api.views.plist_api),
    url(r'^(?P<kind>icons$)', api.views.file_api),
    url(r'^(?P<kind>icons)/(?P<filepath>.*$)', api.views.file_api),
    url(r'^(?P<kind>pkgs$)', api.views.file_api),
    url(r'^(?P<kind>pkgs)/(?P<filepath>.*$)', api.views.file_api),
]

manifests/urls.py
from django.conf.urls import url
import manifests.views

urlpatterns = [
    url(r'^$', manifests.views.index, name='manifests'),
    url(r'^__get_manifest_list_status$', manifests.views.status),
    url(r'^(?P<manifest_path>.*$)', manifests.views.index)
]

manifests/models.py
"""
manifests/models.py
"""
from django.db import models

class ManifestFile(models.Model):
    '''Placeholder so we get permissions entries in the admin database'''
    pass

manifests/views.py
"""
manifests/views.py
"""
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from api.models import Plist, FileDoesNotExistError, FileReadError
from process.models import Process

import json
import logging
import plistlib

LOGGER = logging.getLogger('munkiwebadmin')


def status(request):
    '''Returns status of long-running process'''
    LOGGER.debug('got status request for manifests_list_process')
    status_response = {}
    processes = Process.objects.filter(name='manifests_list_process')
    if processes:
        # display status from one of the active processes
        # (hopefully there is only one!)
        process = processes[0]
        status_response['statustext'] = process.statustext
    else:
        status_response['statustext'] = 'Processing'
    return HttpResponse(json.dumps(status_response),
                        content_type='application/json')


@login_required
def index(request, manifest_path=None):
    '''Returns manifest list or detail'''
    if manifest_path and request.is_ajax():
        # return manifest detail
        if request.method == 'GET':
            LOGGER.debug("Got read request for %s", manifest_path)
            try:
                plist = Plist.read('manifests', manifest_path)
            except (FileDoesNotExistError, FileReadError), err:
                return HttpResponse(
                    json.dumps({'result': 'failed',
                                'exception_type': str(type(err)),
                                'detail': str(err)}),
                    content_type='application/json', status=404)
            manifest_text = plistlib.writePlistToString(plist)
            context = {'plist_text': manifest_text,
                       'pathname': manifest_path}
            return render(request, 'manifests/detail.html', context=context)
        if request.method == 'POST':
            return HttpResponse(
                json.dumps({'result': 'failed',
                            'exception_type': 'MethodNotSupported',
                            'detail': 'POST/PUT/DELETE should use the API'}),
                content_type='application/json', status=404)
    # return list of available manifests
    LOGGER.debug("Got index request for manifests")
    context = {'page': 'manifests',
               'manifest_name': manifest_path}
    return render(request, 'manifests/manifests.html', context=context)

manifests/templates/manifests/detail.html
<h4>{{ pathname }}</h4>
<div class='pull-right' id='delete_btn'>
{% if perms.manifests.delete_manifestfile %}
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteConfirmationModal">Delete</button>
{% endif %}
{% if perms.manifests.change_manifestfile %}
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#copyManifestModal">Duplicate</button>
{% endif %}
</div>
{% if perms.manifests.change_manifestfile %}
<div class='pull-right hidden' id='save_and_cancel'>
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#cancelEditConfirmationModal">Cancel</button>
  <button type="button" class="btn btn-success" onClick="saveManifestItem()">Save</button>
</div>
{% else %}
<div class='pull-right hidden' id='save_and_cancel'>
  <span class="bg-danger">You don't have permissions to make changes here.</span>
  <button type="button" class="btn" onClick="cancelEdit()">Cancel</button>
</div>
{% endif %}
<div role="tabpanel">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist" id="editortabs">
    <li role="presentation" class="active">
      <a href="#basicstab" aria-controls="basicstab" role="tab" data-toggle="tab">Basics</a>
    </li>
    <li role="presentation">
      <a href="#detailtab" aria-controls="editortab" role="tab" data-toggle="tab">Details</a>
    </li>
    <li role="presentation">
      <a href="#plisttab" aria-controls="plisttab" role="tab" data-toggle="tab">plist</a>
    </li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content" id="item_editor">
    <div role="tabpanel" class="tab-pane active" id="basicstab">
        <div id="basics" class="plist-editor"></div>
    </div>
    <div role="tabpanel" class="tab-pane" id="detailtab">
        <div id="detail" class="plist-editor"></div>
    </div>
    <div role="tabpanel" class="tab-pane" id="plisttab">
        <!--<textarea id="p l i s t" rows=30></textarea>-->
        <div id='plist'>{{ plist_text }}</div>
    </div>
   </div>
</div>
<!--
Bootstrap modal for confirming manifest deletion
-->
<div class="modal fade" id="deleteConfirmationModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete manifest?</h4>
      </div>
      <div class="modal-body">
        <p>Really delete <strong>{{ pathname }}</strong>?</p>
        <p>This action cannot be undone.</p>
        <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"  onClick="deleteManifestItem()">Delete</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for confirming canceling editing
-->
<div class="modal fade" id="cancelEditConfirmationModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Discard your changes?</h4>
      </div>
      <div class="modal-body">
        <p>Really discard your changes to <strong>{{ pathname }}</strong>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"  onClick="cancelEdit()">Discard Changes</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Continue Editing</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for saving or canceling when loading a different manifest
-->
<div class="modal fade" id="saveOrCancelConfirmationModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Save your changes?</h4>
      </div>
      <div class="modal-body">
        <p>Save your changes to <strong>{{ pathname }}</strong> before proceeding?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal"  onClick="discardChangesAndLoadNext()">Discard Changes</button>
        <button type="button" class="btn btn-success" data-dismiss="modal" onClick="saveChangesAndLoadNext()">Save Changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for duplicating a manifest
-->
<div class="modal fade" data-backdrop="static" id="copyManifestModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Duplicate manifest</h4>
      </div>
      <div class="modal-body">
        <form id="manifest-duplicate-form">
          <div class="form-group">
            <label for="recipient-name" class="control-label">New manifest name:</label>
            <input type="text" class="form-control" id="manifest-copy-name">
          </div>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="button" data-copy="manifest" class="btn btn-primary">Duplicate</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

manifests/templates/manifests/manifests.html
{% extends 'base.html' %}

{% block extra_style %}
{% load static %}
<link rel="stylesheet" href="{% get_static_prefix %}css/plisteditor.css" type="text/css" media="all" />
<link rel="stylesheet" href="{% get_static_prefix %}manifests/css/manifests.css" type="text/css" media="all" />
{% endblock extra_style %}

{% block java_script %}
{% load static %}
<script type='text/javascript'
    src='{% get_static_prefix %}js/jquery.plisteditor.js'>
</script>
<script type='text/javascript'
    src='{% get_static_prefix %}js/plistparser.js'>
</script>
<script type="text/javascript" charset="utf-8"
    src="{% get_static_prefix %}js/ace/src-min-noconflict/ace.js">
</script>
<script type='text/javascript'
    src='{% get_static_prefix %}js/mwa_editor_shared.js'>
</script>
<script type='text/javascript'
    src='{% get_static_prefix %}manifests/js/manifests.js'>
</script>
{% endblock java_script %}

{% block body_tag %}
<body {% if manifest_name %}onLoad="getManifestItem('{{manifest_name}}')"{% endif %}>
{% endblock %}

{% block content %}
<div class="row-fluid">
  <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
    <div id='item_list'>
        <div class="form-inline">
            <div class="form-group">
                <div class="left-inner-addon">
                    <span class="icon-addon">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </span>
                    <input type="search" class="form-control" id="listSearchField" placeholder="Filter">
                </div>
            </div>
            
            <div class="form-group pull-right">
                  <div class="btn-group">
                      <button type="button" class="btn" data-toggle="modal" data-target="#searchManifestModal">
                          Search manifests
                      </button>
                  </div>
                  {% if perms.manifests.add_manifestfile %}
                  <div class="btn-group">
                      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#newManifestModal">
                          New manifest
                      </button>
                  </div>
                  {% endif %}
            </div>

        </div>
        <table class="table table-striped table-condensed wraptext" id='list_items' style="width:100%">
          <thead>
            <tr><th>Name</th></tr>
          </thead>
          <tbody>
              <!-- table is filled via AJAX/JSON calls by DataTables -->
          </tbody>
        </table>
    </div>
  </div>
  <div class='col-xs-7 col-sm-7 col-md-7 col-lg-7'>
    <div id="manifest_detail"></div>
  </div>
</div>
<!-- data storage -->
<div id="data_storage"/>
<!--
Bootstrap modal for showing progress
-->
<div class="modal fade" data-backdrop="static" id="process_progress">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="process_progress_title_text">Processing...</h4>
      </div>
      <div class="modal-body">
          <div class="progress">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
              <span class="sr-only">Indeterminate progress</span>
              <div id='process_progress_status_text'>&nbsp;</div>
            </div>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
<!--
Bootstrap modal for creating manifests
-->
<div class="modal fade" data-backdrop="static" id="newManifestModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Create new manifest</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="new-manifest-name" class="control-label">Manifest name:</label>
            <input type="text" class="form-control" id="new-manifest-name">
          </div>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="button" data-new="manifest" class="btn btn-primary">Create</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
<!--
Bootstrap modal for searching inside manifests
-->
<div class="modal fade" data-backdrop="static" id="searchManifestModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Search</h4>
      </div>
      <div class="modal-body">
        <form id='search_parameters'>
          <div class="form-group">
            <label for="manifest-search-text" class="control-label">Search text:</label>
            <input type="text" class="form-control" id="manifest-search-text" name="search_text">
          </div>
          <div class="form-group">
              <label for="manifest-section-choice" class="control-label">Manifest section:</label>
              <select class="form-control" id="manifest-search-section" name="search_section">
                  <option value='managed_installs'>Managed Installs</option>
                  <option value='managed_uninstalls'>Managed Uninstalls</option>
                  <option value='managed_updates'>Managed Updates</option>
                  <option value='optional_installs'>Optional Installs</option>
                  <option value='included_manifests'>Included Manifests</option>
                  <option value='catalogs'>Catalogs</option>
              </select>
        </div>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" id='manifest_search_btn'>Search</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
<!--
Bootstrap modal for errors
-->
<div class="modal fade" data-backdrop="static" id="errorModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-danger">
            <span class="glyphicon glyphicon-alert text-danger" aria-hidden="true"></span>
            <span id="errorModalTitleText">Error</span>
        </h4>
      </div>
      <div class="modal-body">
        <form>
          <p id="errorModalDetailText">An unexpected error occurred.</p>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
{% endblock content %}